[Application]
  ServiceName = sensor-service
  Port        = 9000

[Database]
  Host                  = 127.0.0.1
  Port                  = 3306
  User                  = root
  Password              =
  Name                  = test
  MaxIdleConnection     = 10
	MaxOpenConnection     = 100
	MaxLifetimeConnection = 60
	MaxIdletimeConnection = 60

[GRPC]
  Host    = localhost
  Port    = 50001